language: python
python:
  - "3.5"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
before_install:
  - pip install pipenv
install:
  - travis_retry pipenv sync --dev
script:
  - pipenv run -- pytest --cov-report term-missing:skip-covered --cov .
